name: CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  #----------------------------------------------
  #       Cache Virtual Environment
  #----------------------------------------------
  venv-setup:
    name: Cache Venv
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: |
        python -m pip list
        python --version
        echo "Successfully setup venv"

  #----------------------------------------------
  #       Run Black
  #----------------------------------------------
  black:
    name: Black
    needs: venv-setup
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m black --check .

  #----------------------------------------------
  #       Run Isort
  #----------------------------------------------
  isort:
    name: Isort
    needs: venv-setup
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m isort --check-only .

  #----------------------------------------------
  #       Run Mypy
  #----------------------------------------------
  mypy:
    name: Mypy
    needs: venv-setup
    if: false  # This condition ensures the job is never executed
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m mypy --verbose 0 .

  #----------------------------------------------
  #       Run Flake8
  #----------------------------------------------
  flake8:
    name: Flake8
    needs: venv-setup
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m flake8 .

  #----------------------------------------------
  #       Run Unittests
  #----------------------------------------------
  unittest:
    name: Unittest
    needs: [
      venv-setup,
      black,
      isort,
      mypy,
      flake8,
    ]
    if: false  # This condition ensures the job is never executed
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: pytest tests/
