name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  #----------------------------------------------
  #                Build Environment
  #----------------------------------------------
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      command: |
        python -m pip list
        python --version
        echo "Build successful"

  #----------------------------------------------
  #                 Run Linters
  #----------------------------------------------
  lint-black:
    name: Linter (Black)
    needs: build
    uses: ./.github/workflows/build.yml
    with:
      command: python -m black --check .
  lint-isort:
    name: Linter (Isort)
    needs: build
    uses: ./.github/workflows/build.yml
    with:
      command: python -m isort --check-only .
  lint-mypy:
    name: Linter (Mypy)
    needs: build
    if: false  # This condition ensures the job is never executed
    uses: ./.github/workflows/build.yml
    with:
      command: python -m mypy --verbose 0 .
  lint-flake8:
    name: Linter (Flake8)
    needs: build
    uses: ./.github/workflows/build.yml
    with:
      command: python -m flake8 .

  #----------------------------------------------
  #                 Run Tests
  #----------------------------------------------
  test-unittest:
    name: Tests (Unittest)
    needs: [
      lint-black,
      lint-isort,
      lint-mypy,
      lint-flake8,
    ]
    # `always` will run the tests regardless of linting success
    if: ${{ always() }} & false # This condition ensures the job is never executed
    uses: ./.github/workflows/build.yml
    with:
      command: pytest tests/
