name: CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  #----------------------------------------------
  #          Cache Virtual Environment
  #----------------------------------------------
  venv-setup:
    name: Cache Venv
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: |
        python -m pip list
        python --version
        echo "Successfully setup venv"

  #----------------------------------------------
  #       Run Black
  #----------------------------------------------
  black:
    name: Black
    needs: venv-setup
    runs-on: ubuntu-latest
    steps:

      #------------------------------------------------
      #       check-out repo and set-up python
      #------------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      #------------------------------------------------
      #        Run custom command(s) within venv
      #------------------------------------------------
      - name: Run commands
        run: |
          echo "Attempting Black Run"
          ls -al
          source .venv/bin/activate
          python -m black --check .

  #----------------------------------------------
  #       Run Isort
  #----------------------------------------------
  isort:
    name: Isort
    needs: venv-setup
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m isort --check-only .

  #----------------------------------------------
  #       Run Mypy
  #----------------------------------------------
  mypy:
    name: Mypy
    needs: venv-setup
    if: false  # This condition ensures the job is never executed
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m mypy --verbose 0 .

  #----------------------------------------------
  #       Run Flake8
  #----------------------------------------------
  flake8:
    name: Flake8
    needs: venv-setup
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: python -m flake8 .

  #----------------------------------------------
  #       Run Unittests
  #----------------------------------------------
  unittest:
    name: Unittest
    needs: [
      venv-setup,
      black,
      isort,
      mypy,
      flake8,
    ]
    if: false  # This condition ensures the job is never executed
    uses: ./.github/workflows/reusable_cache.yml
    with:
      command: pytest tests/
